import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import AppHeader from "@/components/AppHeader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cứu hộ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="vi">
        <link rel="dns-prefetch" href="https://maps.vietmap.vn" />
        <link rel="preconnect" href="https://maps.vietmap.vn" crossOrigin="" />

        <body className="antialiased bg-gray-50">
        {/* Header đặt cố định cao 64px → ta bọc main có top padding */}
        <div className="sticky top-0 z-40 bg-white border-b">
            <AppHeader />
        </div>
        <main className="px-4 md:px-6 lg:px-8 py-6">{children}</main>
        <Toaster richColors position="top-right" />
        </body>
        </html>
    );
}
